### ISSUE TITLE
Unhandled Exception: System.Exception: Unable to find crypto stream TypeDef

### ISSUE THREAD

**Issue by Masterxv** [saneki/eazdevirt#8]
Unhandled Exception: System.Exception: Unable to find crypto stream TypeDef

Unhandled Exception: System.Exception: Unable to find crypto stream TypeDef
   at eazdevirt.EazModule.Initialize() in E:\xxxx\eazdevirt-master\src\eazdevirt\Core\EazModule.cs:line 86
   at eazdevirt.EazModule..ctor(ModuleDefMD module, ILogger logger) in E:\xxx\eazdevirt-master\src\eazdevirt\Core\EazModule.cs:line 77
   at eazdevirt.Program.TryLoadModule(String path, ILogger logger, EazModule& module) in E:\xxx\eazdevirt-master\src\eazdevirt\Program.cs:line 192
   at eazdevirt.Program.DoDevirtualize(MonoOptions options) in E:\xxx\eazdevirt-master\src\eazdevirt\Program.Devirtualize.cs:line 168
   at eazdevirt.Program.Main(String[] args) in E:\xxx\eazdevirt-master\src\eazdevirt\Program.cs:line 139

**Comment by Numenorean** [comment]
I got this too

**Comment by Slowftw** [comment]
i think it's patched

**Comment by sasha2002** [comment]
Same, trying to fix but no luck.
@saneki Did you have working version? Or can you fix it?
Or point please in what direction need to look.

**Comment by ntqueryinformation** [comment]
Same issue, have not found a solution at al. Any pointers?

**Comment by Marsel-marsel** [comment]
This exception throws explicitly in EazModule.Initialize()
`
private void Initialize()
{
	// Initialize PositionTranslator
	var cryptoStreamDef = this.FindCryptoStreamType();
	if (cryptoStreamDef == null)
		throw new Exception("Unable to find crypto stream TypeDef");
`
Maybe we can figure out what is the missing crypto stream?
